# Generated by Django 5.2.8 on 2025-11-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_notice_notice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_logo1',
            field=models.ImageField(blank=True, null=True, upload_to='office_logo/'),
        ),
    ]
