# Generated by Django 5.2.8 on 2025-11-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_office_office_logo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_logo',
            field=models.ImageField(blank=True, null=True, upload_to='office_logo/'),
        ),
    ]
