# Generated by Django 5.2.8 on 2025-11-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_office_office_phone_office_ofice_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='ofice_email',
            new_name='office_email',
        ),
    ]
